### ISSUE TITLE
👑 [需求]支持本地模型

### ISSUE THREAD

**Issue by JChuan128** [yuruotong1/xbrain#10]
### 🥰 需求描述

目前仅支持OpenAI，不支持本地模型
![image](https://github.com/user-attachments/assets/0fedd10e-c2c3-46ff-be3f-fd362cf2da46)
### 🧐 解决方案

1、部分模型（如qwen）需要使用特定的工具调用模板

**Comment by JChuan128** [comment]
ignore this iussue, 换到了qwen2.5模型，使用vllm serve Qwen/Qwen2.5-7B-Instruct --enable-auto-tool-choice --tool-call-parser hermes启动模型解决

**Comment by yuruotong1** [comment]
> 持本地模型
OK，方便大概提供一下解决思路嘛，我写到readme上
